class NationalityEN {
    data = [{value: 3, label: "Albania"},
        {value: 4, label: "Algeria"},
        {value: 5, label: "Andorra"},
        {value: 1, label: "Angola"},
        {value: 6, label: "Anguilla"},
        {value: 7, label: "Antigua and Barbuda"},
        {value: 400, label: 'Andorra'},
        {value: 401, label: 'Afghanistan'},
        {value: 402, label: 'American Samoa'},
        {value: 8, label: "Argentina"},
        {value: 9, label: "Armenia"},
        {value: 194, label: "Aruba"},
        {value: 10, label: "Ascension"},
        {value: 11, label: "Australia"},
        {value: 195, label: "Australianoverseasterritories"},
        {value: 12, label: "Austria"},
        {value: 13, label: "Azerbaijan"},
        {value: 14, label: "Bahamas"},
        {value: 15, label: "Bahrain"},
        {value: 17, label: "Barbados"},
        {value: 302, label: "Bangladesh"},
        {value: 19, label: "Belgium"},
        {value: 403, label: 'Bolivia'},
        {value: 404, label: 'Belarus'},
        {value: 20, label: "Belize"},
        {value: 21, label: "Benin"},
        {value: 22, label: "Bermuda"},
        {value: 196, label: "Bhutan"},
        {value: 197, label: "BosniaandHerzegovina"},
        {value: 24, label: "Botswana"},
        {value: 25, label: "Brazil"},
        {value: 229, label: "British Virgin Islands"},
        {value: 26, label: "Brunei"},
        {value: 27, label: "Bulgaria"},
        {value: 28, label: "Burkina Faso"},
        {value: 30, label: "Burundi"},
        {value: 85, label: "Cambodia"},
        {value: 32, label: "Canada"},
        {value: 198, label: "CapeVerde"},
        {value: 33, label: "Cayman Islands."},
        {value: 405, label: 'Central African Republic'},
        {value: 427, label: 'Chad'},
        {value: 408, label: 'Cameroon'},
        {value: 409, label: 'Cuba'},
        {value: 36, label: "Chile"},
        {value: 37, label: "China"},
        {value: 38, label: "Colombia"},
        {value: 199, label: "ComorosIslands"},
        {value: 40, label: "Cook Islands."},
        {value: 41, label: "Costa Rica"},
        {value: 200, label: "Croatia"},
        {value: 43, label: "Cyprus"},
        {value: 44, label: "Czech Republic"},
        {value: 45, label: "Denmark"},
        {value: 201, label: "DiegoGarcia"},
        {value: 46, label: "Djibouti"},
        {value: 410, label: 'Dominica'},
        {value: 47, label: "Dominican Republic"},
        {value: 202, label: "EastTimor"},
        {value: 49, label: "Egypt"},
        {value: 411, label: 'Ecuador'},
        {value: 50, label: "El Salvador"},
        {value: 230, label: "Emirate of Dubai"},
        {value: 203, label: "EquatorialGuinea"},
        {value: 204, label: "Eritrea"},
        {value: 51, label: "Estonia"},
        {value: 52, label: "Ethiopia"},
        {value: 205, label: "FalklandIslands"},
        {value: 206, label: "FaroeIslands"},
        {value: 53, label: "Fiji"},
        {value: 54, label: "Finland"},
        {value: 55, label: "France"},
        {value: 56, label: "French Guiana"},
        {value: 136, label: "French Polynesia"},
        {value: 57, label: "Gabon"},
        {value: 58, label: "Gambia"},
        {value: 59, label: "Georgia"},
        {value: 412, label: 'Guinea'},
        {value: 60, label: "Germany"},
        {value: 61, label: "Ghana"},
        {value: 62, label: "Gibraltar"},
        {value: 63, label: "Greece"},
        {value: 207, label: "Greenland"},
        {value: 64, label: "Grenada"},
        {value: 208, label: "Guadeloupe"},
        {value: 65, label: "Guam"},
        {value: 66, label: "Guatemala"},
        {value: 209, label: "Guinea-Bissau"},
        {value: 68, label: "Guyana"},
        {value: 69, label: "Haiti"},
        {value: 70, label: "Honduras"},
        {value: 71, label: "Hong Kong (China)"},
        {value: 72, label: "Hungary"},
        {value: 73, label: "Iceland"},
        {value: 74, label: "India"},
        {value: 75, label: "Indonesia"},
        {value: 231, label: "Iran"},
        {value: 78, label: "Ireland"},
        {value: 79, label: "Israel"},
        {value: 80, label: "Italy"},
        {value: 413, label: 'Iraq'},
        {value: 407, label: 'Ivory Coast'},
        {value: 301, label: "Japan"},
        {value: 82, label: "Jamaica"},
        {value: 84, label: "Jordan"},
        {value: 86, label: "Kazakstan"},
        {value: 87, label: "Kenya"},
        {value: 415, label: 'Korea Democratic Rep.'},
        {value: 210, label: "Kiribati"},
        {value: 88, label: "Korea"},
        {value: 89, label: "Kuwait"},
        {value: 90, label: "Kyrgyzstan"},
        {value: 91, label: "Laos"},
        {value: 92, label: "Latvia"},
        {value: 94, label: "Lesotho"},
        {value: 97, label: "Liechtenstein"},
        {value: 98, label: "Lithuania"},
        {value: 99, label: "Luxembourg"},
        {value: 416, label: 'Lebanon'},
        {value: 417, label: 'Liberia'},
        {value: 418, label: 'Libya'},
        {value: 211, label: "Macedonia"},
        {value: 101, label: "Madagascar"},
        {value: 102, label: "Malawi"},
        {value: 103, label: "Malaysia"},
        {value: 104, label: "Maldives"},
        {value: 105, label: "Mali"},
        {value: 106, label: "Malta"},
        {value: 107, label: "Mariana Islands"},
        {value: 212, label: "Marshall Islands"},
        {value: 108, label: "Martinique"},
        {value: 213, label: "Mauritania"},
        {value: 109, label: "Mauritius"},
        {value: 110, label: "Mexico"},
        {value: 214, label: "Micronesia"},
        {value: 111, label: "Moldova"},
        {value: 112, label: "Monaco"},
        {value: 419, label: 'Myanmar'},
        {value: 420, label: 'Macau'},
        {value: 113, label: "Mongolia"},
        {value: 215, label: "Montenegro"},
        {value: 114, label: "Montserrat"},
        {value: 115, label: "Morocco"},
        {value: 116, label: "Mozambique"},
        {value: 117, label: "Namibia"},
        {value: 118, label: "Nauru"},
        {value: 119, label: "Nepal"},
        {value: 120, label: "Netheriands Antilles"},
        {value: 121, label: "Netherlands"},
        {value: 122, label: "New Zealand"},
        {value: 216, label: "NewCaledonia"},
        {value: 123, label: "Nicaragua"},
        {value: 124, label: "Niger"},
        {value: 125, label: "Nigeria"},
        {value: 217, label: "Niue"},
        {value: 127, label: "Norway"},
        {value: 128, label: "Oman"},
        {value: 218, label: "Palau"},
        {value: 219, label: "Palestine"},
        {value: 130, label: "Panama"},
        {value: 131, label: "Papua New Cuinea"},
        {value: 132, label: "Paraguay"},
        {value: 133, label: "Peru"},
        {value: 134, label: "Philippines"},
        {value: 135, label: "Poland"},
        {value: 137, label: "Portugal"},
        {value: 406, label: 'Republic Of The Congo'},
        {value: 421, label: 'Pakistan'},
        {value: 422, label: 'Puerto Rico'},
        {value: 138, label: "Puerto Rico"},
        {value: 139, label: "Qatar"},
        {value: 140, label: "Reunion"},
        {value: 141, label: "Romania"},
        {value: 142, label: "Russia"},
        {value: 220, label: "Rwanda"},
        {value: 143, label: "Saint Lueia"},
        {value: 144, label: "Saint Vincent"},
        {value: 222, label: "SaintPierreandMiquelon"},
        {value: 145, label: "Samoa Eastern"},
        {value: 146, label: "Samoa Western"},
        {value: 147, label: "San Marino"},
        {value: 148, label: "Sao Tome and Principe"},
        {value: 149, label: "Saudi Arabia"},
        {value: 150, label: "Senegal"},
        {value: 223, label: "Serbia"},
        {value: 151, label: "Seychelles"},
        {value: 152, label: "Sierra Leone"},
        {value: 153, label: "Singapore"},
        {value: 154, label: "Slovakia"},
        {value: 155, label: "Slovenia"},
        {value: 156, label: "Solomon Islands"},
        {value: 158, label: "South Africa"},
        {value: 159, label: "Spain"},
        {value: 160, label: "Sri Lanka"},
        {value: 221, label: "St.Helena"},
        {value: 161, label: "St.Lucia"},
        {value: 423, label: 'Sudan'},
        {value: 424, label: 'Somalia'},
        {value: 425, label: 'Syria'},
        {value: 414, label: 'Saint Kitts and Nevis'},
        {value: 162, label: "St.Vincent"},
        {value: 164, label: "Suriname"},
        {value: 165, label: "Swaziland"},
        {value: 166, label: "Sweden"},
        {value: 167, label: "Switzerland"},
        {value: 169, label: "Taiwan (China)"},
        {value: 170, label: "Tajikstan"},
        {value: 171, label: "Tanzania"},
        {value: 172, label: "Thailand"},
        {value: 173, label: "Togo"},
        {value: 224, label: "Tokelau"},
        {value: 174, label: "Tonga"},
        {value: 175, label: "Trinidad and Tobago"},
        {value: 176, label: "Tunisia"},
        {value: 177, label: "Turkey"},
        {value: 178, label: "Turkmenistan"},
        {value: 426, label: 'Turksand Caicos Islands'},
        {value: 225, label: "Tuvalu"},
        {value: 179, label: "Uganda"},
        {value: 180, label: "Ukraine"},
        {value: 300, label: "United States of America"},
        {value: 181, label: "United Arab Emirates"},
        {value: 182, label: "United Kingdom"},
        {value: 184, label: "Uruguay"},
        {value: 185, label: "Uzbekistan"},
        {value: 226, label: "Vanuatu"},
        {value: 227, label: "VaticanCity"},
        {value: 186, label: "Venezuela"},
        {value: 187, label: "Vietnam"},
        {value: 228, label: "WallisandFutuna"},
        {value: 189, label: "Yugoslavia"},
        {value: 428, label: 'Yemen'},
        {value: 192, label: "Zaire"},
        {value: 429, label: 'Zimbabwe'},
        {value: 193, label: "Zambia"}]
}

export default NationalityEN